version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:80 testing.wsgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=testing.settings
